version: "3"

services:

    web:
        image: nginx
        build: ./nginx

        ports: 
            - 8080:80

    python:
        image: ghcr.io/opendrr/python-env:1.2.1
        build: ./python

    # kibana:
    #     image: kibana:8.2.3
        
    #     environment:
    #         ELASTICSEARCH_HOSTS: http://elasticsearch:9200

    #     ports: 
    #         - 5601:5601
        
    #     depends_on: 
    #         - elasticsearch
    
    elasticsearch: 
        image: elasticsearch:8.2.3
        
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - "http.cors.allow-origin=http://localhost:8080"
            - "http.cors.enabled=true"
            - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
            - "http.cors.allow-credentials=true"
        
        ports: 
            - 9200:9200

        restart: unless-stopped
